Repository Thfirmin/cub3D, pull requests merged in 2023-05, with the labels that each got.

#5 Add folder to parse and moved FD to main function
  includes/parse.h
  srcs/cub3d.c
  srcs/parse/parse.c
Labels: feature

#6 Feat (Documetation): New text to README.md
  README.md
Labels: documentation

#8 Fix vars
  includes/cub3d.h
Labels: bug
